from selenium import webdriver
browser = webdriver.Firefox()
browser.get('https://www.cure.fit/login?redirect=me#loginModal')
from selenium.webdriver.common.action_chains import ActionChains
bangalore = browser.find_element_by_xpath('/html/body/div[4]/div[2]/div/div/div/div[1]/div/div[1]')
Hover = ActionChains(browser).move_to_element(bangalore)
Hover.click().perform()
submit = browser.find_element_by_xpath('/html/body/div[4]/div[2]/div/div/div/div[2]/button')
Hover = ActionChains(browser).move_to_element(submit)
Hover.click().perform()
submit = browser.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[6]/div/div/div/div/div/div[2]/div/div[3]/div[1]')
Hover = ActionChains(browser).move_to_element(submit)
Hover.click().perform()
submit = browser.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[6]/div/div/div/div/div/form/input[1]')
submit.send_keys('mdd.akram@gmail.com')
submit = browser.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[6]/div/div/div/div/div/form/input[2]')
submit.send_keys('akram.captain')
submit = browser.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[6]/div/div/div/div/div/form/div/input')
Hover = ActionChains(browser).move_to_element(submit)
Hover.click().perform()
browser.get('https://www.cure.fit/cult/classbooking/20?centerId=20&pageType=classbooking')
submit = browser.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[3]/div/div[1]/div/div[2]/div/div[3]/div[1]/div/div[1]/div[4]/div/div')
Hover = ActionChains(browser).move_to_element(submit)
Hover.click().perform()

